---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
       update_cache: yes


  - name: install node package
    apt:
      name: nodejs
      state: absent


  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent

